<?php

/**
 * @file
 * Contains ejikznayka_registration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;
use Drupal\Component\Utility\Random;

/**
 * Implements hook_help().
 */
function ejikznayka_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ejikznayka_registration module.
    case 'help.page.ejikznayka_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides registration with referrals.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ejikznayka_registration_form_user_register_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['ejikznayka_registration_hash'] = array(
    '#type' => 'textfield',
    '#title' => t('Referral code'),
    '#size' => 32,
    '#maxlength' => 32,
    '#weight' => 3,
    '#description' => t('Put here the code you received from the person who invited you to sign up.'),
  );
  $form['#validate'][] = 'ejikznayka_registration_form_validate';
  $form['actions']['submit']['#submit'][] = 'ejikznayka_registration_form_submit';
}

function ejikznayka_registration_form_validate(&$form, FormStateInterface $form_state) {
  if (!empty($form_state->getValue('ejikznayka_registration_hash'))
    && strlen($form_state->getValue('ejikznayka_registration_hash')) != 32) {
    $form_state->setErrorByName('ejikznayka_registration_hash', t('Incorrect format of registration code.'));
  }
}

/**
 * Custom form submit callback to set user reference.
 *
 * @see ejikznayka_registration_form_user_register_form_alter()
 */
function ejikznayka_registration_form_submit(&$form, FormStateInterface $form_state) {
  $query = \Drupal::entityQuery('user');
  $result = $query->condition('field_ejikznayka_referral_code', $form_state->getValue('ejikznayka_registration_hash'))->execute();
  if (count($result) > 1) {
    // Bad practice. We should have created our dedicated exception class and provide catch block.
    throw new \Exception('Several users with the same referral code.');
  }

  if (!empty($result)) {
    $form_state->getFormObject()->getEntity()->set('field_ejikznayka_referral_user', $result[array_keys($result)[0]])->save();
  }
}

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function ejikznayka_registration_user_create(User $user) {
  $user->set('field_ejikznayka_referral_code', Random::string(32));
}
